language: objective-c
osx_image: xcode7.3

before_install:
  - bundle install
	    
script:
  - set -o pipefail && xcodebuild clean build test -project MyWeight.xcodeproj -scheme MyWeight -destination "platform=iOS Simulator,name=iPhone 5s,OS=9.3" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
  - bundle exec danger

notifications:
  email: false
