language: objective-c
osx_image: xcode7.3

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  
script:
  - xcodebuild clean build test -project MyWeight.xcodeproj -scheme MyWeight -destination "platform=iOS Simulator,name=iPhone 5s,OS=9.3" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

notifications:
  email: false
