name: 'Tests'

on:
  pull_request:
    type: [opened, synchronize, reopened]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: 'Run Tests'
    runs-on: macos-14
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: 'Setup environment'
        run: rake setup
        shell: bash

      - name: 'Test'
        run: bundle exec rake xcode:tests[true]
        shell: bash
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
